### ISSUE TITLE
Amount must be greater than 0 

### ISSUE THREAD

**Issue by priyanka795** [DIBS-Payment-Services/Magento1_easy#15]
@maxwhite @anknudse @Corefix @TheisCorfixenVaimo @bogudibs  
I created a recurring product. It throws an error during checkout is Amount must be greater than 0

Dibs_EasyPayment_Api_Exception_Response Object ( [message:protected] => Amount must be greater than 0 [string:Exception:private] => exception 'Dibs_EasyPayment_Api_Exception_Response' with message 'Amount must be greater than 0' in /home/nybomvinewsisite/public_html/lib/Dibs/EasyPayment/Api/Client.php:111 Stack trace: #0 /home/nybomvinewsisite/public_html/lib/Dibs/EasyPayment/Api/Client.php(86): Dibs_EasyPayment_Api_Client->prepareResponse(Resource id #524) #1 /home/nybomvinewsisite/public_html/lib/Dibs/EasyPayment/Api/Service/Action/Payment/Create.php(63):

Let me know how I can investigate the issue further.
Thanks

**Comment by maxwhite** [comment]
doesn't support recurring payment
